spring:
  datasource:
    url: jdbc:mysql://192.168.0.107:3306/ht_shop_test?characterEncoding=utf-8&allowMultiQueries=true
    username: root
    password: yymyroot
    driverClassName: com.mysql.jdbc.Driver

  thymeleaf:
     cache: false
debug: true

server:
  port: 8081